package common

const BASE_TEN = 10
const UINT_16_SIZE = 16

const STATIC_FILES_PATH_ENV_VAR_NAME = "TESTSERVER_STATICFILES_PATH"
const STATIC_FILES_DEFAULT_PATH = "./web/static"

const SERVER_PORT_ENV_VAR_NAME = "TESTSERVER_PORT"
const SERVER_DEFAULT_PORT = "8000"
